#!/bin/bash
#
# Init script to start and stop BUSY backup system
#
#

NAME=busyd
DAEMON=/usr/local/bin/$NAME
DESC="Centralized LAN backup system"

[ -x "$DAEMON" ] || exit 0

case "$1" in
	start)
		echo -n "Starting $NAME"
		$DAEMON
		if [ $? -eq 0 ] ; then
			echo "[OK]"
		else
			echo "[FAIL]"
			exit -1
		fi
		;;
	
	stop)
		echo "Stopping $NAME"
		for FILE in /var/lock/busy/* ; do
			PID=$(basename "${FILE}")
			kill -9 ${PID}
			rm "${FILE}"
		done
		echo "[DONE]"
		;;
	
	reload|restart)
		$0 stop && $0 start
		;;
		
	*)
		echo "Usage: /etc/init.d/$NAME {start|stop|restart|reload}" >&2
		exit 1
		;;
esac

