#!/bin/bash
#
# Init script to start and stop BUSY backup system
#
#

NAME=busy
DAEMON=/usr/local/bin/busyd
DESC="Centralized LAN backup system"

if [ $(whoami) != "root" ] ; then
	echo "This script must be run as root. Exiting."
	exit
fi


[ -x "$DAEMON" ] || exit 0

case "$1" in
	start)
		echo -n "Starting $NAME"
		$DAEMON
		if [ $? -eq 0 ] ; then
			echo " [OK]"
		else
			echo " [FAIL]"
			exit -1
		fi
		;;
	
	stop)
		echo "Stopping $NAME"
		killall -9 busyd
		rm -f /var/lock/busy/*
		echo " [DONE]"
		;;
	
	reload|restart)
		$0 stop && $0 start
		;;
		
	*)
		echo "Usage: /etc/init.d/$NAME {start|stop|restart|reload}" >&2
		exit 1
		;;
esac

